// Angel One Symbol Tokens for NSE/BSE stocks
const STOCK_TOKENS = {
  // NSE Stocks
  'RELIANCE': { token: '2885', exchange: 'NSE', tradingSymbol: 'RELIANCE-EQ' },
  'TCS': { token: '11536', exchange: 'NSE', tradingSymbol: 'TCS-EQ' },
  'HDFCBANK': { token: '1333', exchange: 'NSE', tradingSymbol: 'HDFCBANK-EQ' },
  'INFY': { token: '1594', exchange: 'NSE', tradingSymbol: 'INFY-EQ' },
  'ICICIBANK': { token: '4963', exchange: 'NSE', tradingSymbol: 'ICICIBANK-EQ' },
  'WIPRO': { token: '3787', exchange: 'NSE', tradingSymbol: 'WIPRO-EQ' },
  'HINDUNILVR': { token: '1394', exchange: 'NSE', tradingSymbol: 'HINDUNILVR-EQ' },
  'TATASTEEL': { token: '3499', exchange: 'NSE', tradingSymbol: 'TATASTEEL-EQ' },
  'BAJFINANCE': { token: '317', exchange: 'NSE', tradingSymbol: 'BAJFINANCE-EQ' },
  'SBIN': { token: '3045', exchange: 'NSE', tradingSymbol: 'SBIN-EQ' },
  'ADANIENT': { token: '25', exchange: 'NSE', tradingSymbol: 'ADANIENT-EQ' },
  'ASIANPAINT': { token: '236', exchange: 'NSE', tradingSymbol: 'ASIANPAINT-EQ' },
  'MARUTI': { token: '10999', exchange: 'NSE', tradingSymbol: 'MARUTI-EQ' },
  'SUNPHARMA': { token: '3351', exchange: 'NSE', tradingSymbol: 'SUNPHARMA-EQ' },
  'ONGC': { token: '2475', exchange: 'NSE', tradingSymbol: 'ONGC-EQ' },
  'BHARTIARTL': { token: '10604', exchange: 'NSE', tradingSymbol: 'BHARTIARTL-EQ' },
  'NESTLEIND': { token: '17963', exchange: 'NSE', tradingSymbol: 'NESTLEIND-EQ' },
  'LTIM': { token: '17818', exchange: 'NSE', tradingSymbol: 'LTIM-EQ' },
  'TITAN': { token: '3506', exchange: 'NSE', tradingSymbol: 'TITAN-EQ' },
  'ULTRACEMCO': { token: '11532', exchange: 'NSE', tradingSymbol: 'ULTRACEMCO-EQ' },
  // Extra popular stocks
  'HCLTECH': { token: '1363', exchange: 'NSE', tradingSymbol: 'HCLTECH-EQ' },
  'KOTAKBANK': { token: '1922', exchange: 'NSE', tradingSymbol: 'KOTAKBANK-EQ' },
  'LT': { token: '11483', exchange: 'NSE', tradingSymbol: 'LT-EQ' },
  'AXISBANK': { token: '5900', exchange: 'NSE', tradingSymbol: 'AXISBANK-EQ' },
  'BAJAJFINSV': { token: '16675', exchange: 'NSE', tradingSymbol: 'BAJAJFINSV-EQ' },
  'TECHM': { token: '13538', exchange: 'NSE', tradingSymbol: 'TECHM-EQ' },
  'POWERGRID': { token: '14977', exchange: 'NSE', tradingSymbol: 'POWERGRID-EQ' },
  'NTPC': { token: '11630', exchange: 'NSE', tradingSymbol: 'NTPC-EQ' },
  'COALINDIA': { token: '20374', exchange: 'NSE', tradingSymbol: 'COALINDIA-EQ' },
  'TATAMOTORS': { token: '3456', exchange: 'NSE', tradingSymbol: 'TATAMOTORS-EQ' },
  'DRREDDY': { token: '881', exchange: 'NSE', tradingSymbol: 'DRREDDY-EQ' },
  'CIPLA': { token: '694', exchange: 'NSE', tradingSymbol: 'CIPLA-EQ' },
  'EICHERMOT': { token: '910', exchange: 'NSE', tradingSymbol: 'EICHERMOT-EQ' },
  'HEROMOTOCO': { token: '1348', exchange: 'NSE', tradingSymbol: 'HEROMOTOCO-EQ' },
  'DIVISLAB': { token: '10940', exchange: 'NSE', tradingSymbol: 'DIVISLAB-EQ' },
  'GRASIM': { token: '1232', exchange: 'NSE', tradingSymbol: 'GRASIM-EQ' },
  'BPCL': { token: '526', exchange: 'NSE', tradingSymbol: 'BPCL-EQ' },
  'INDUSINDBK': { token: '5258', exchange: 'NSE', tradingSymbol: 'INDUSINDBK-EQ' },
  'JSWSTEEL': { token: '11723', exchange: 'NSE', tradingSymbol: 'JSWSTEEL-EQ' },
  'TATACONSUM': { token: '3432', exchange: 'NSE', tradingSymbol: 'TATACONSUM-EQ' },
  'APOLLOHOSP': { token: '157', exchange: 'NSE', tradingSymbol: 'APOLLOHOSP-EQ' },
  'ADANIPORTS': { token: '15083', exchange: 'NSE', tradingSymbol: 'ADANIPORTS-EQ' },
  'HINDALCO': { token: '1363', exchange: 'NSE', tradingSymbol: 'HINDALCO-EQ' },
  'SBILIFE': { token: '21808', exchange: 'NSE', tradingSymbol: 'SBILIFE-EQ' },
  'HDFCLIFE': { token: '467', exchange: 'NSE', tradingSymbol: 'HDFCLIFE-EQ' },
  'UPL': { token: '11287', exchange: 'NSE', tradingSymbol: 'UPL-EQ' },
  'BRITANNIA': { token: '547', exchange: 'NSE', tradingSymbol: 'BRITANNIA-EQ' },
  'SHREECEM': { token: '3103', exchange: 'NSE', tradingSymbol: 'SHREECEM-EQ' },
  'ICICIGI': { token: '15083', exchange: 'NSE', tradingSymbol: 'ICICIGI-EQ' },
  'MCDOWELL-N': { token: '2534', exchange: 'NSE', tradingSymbol: 'MCDOWELL-N-EQ' },
};

module.exports = { STOCK_TOKENS };
